name: 'get version name'
on:
  workflow_dispatch:
    inputs:
      project_name:
        type: string
        description: 'The repository name accessed from JIRA Issue description'
        required:    true   
      version:
        type: string
        description: 'The name of the repository to be created'
        required:    true       


env:
  OWNER: amitbind13
  BRANCH: main
        
jobs:
  trigger_action:
    runs-on: ubuntu-latest
    steps:
      - name: Calling version data
        id:  latest_version
        run: |
          curl --request POST \n
          --url 'https://prashantb02.atlassian.net/projects/HP' \n
          --user 'amitkumarbind130207@gmail.com:w9Qi8fSPDD1h76ELBfo9DF8E' \n
          --header 'Accept: application/json'


        
      - name: JIRA Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}


           
          


        
        
       
          
