name: 'pull-request-v1 action'
on:
  workflow_dispatch:
    inputs:
      project_name:
        type: string
        description: 'The repository name accessed from JIRA Issue description'
        required:    true   
      version:
        type: string
        description: 'The name of the repository to be created'
        required:    true       


env:
  OWNER: amitbind13
  BRANCH: main
        
jobs:
  trigger_action:
    runs-on: ubuntu-latest
    steps:
      - name: Calling version data
        id:  latest_version
        run: |
          curl -X POST -H "Authorization:${{secrets.JIRA_TOKEN}}" -H "Accept:application/vnd.github.v3+json" -o repos.json  https://api.github.com/repos/prashant-demo110/${{ github.event.inputs.project_name }}/pulls -d '{"title":"Releases","body":"Please pull these awesome changes in!","head":"prashant-demo110:${{ github.event.inputs.jirareleaseversion}}","base":"main"}'
          errorMessage="$(jq -r '.message' repos.json)"
          errorDetail="$(jq -r '.errors[0].message' repos.json)"


        
      - name: JIRA Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Jira Add Comment
        uses: atlassian/gajira-comment@v2.0.2
        with:
          issue: ${{ github.event.inputs.jiraId }}
          comment:  ${{ steps.createPullRequestId.outputs.webhookData.versionName }}
        
           
          


        
        
       
          
